### ISSUE TITLE
How to change cell size.??

### ISSUE THREAD

**Issue by cloudjanak** [uzysjung/UzysGridView#1]

**Comment by uzysjung** [comment]
I made it long time ago. 
This repository is not actively maintained currently.

cell size is determined by number of row, number of column , cell margin automatically  when you initialize UzysGridview.

**Comment by cloudjanak** [comment]
and how to detect which cell in clicked..??

**Comment by uzysjung** [comment]
you can use Delegate method below
-(void) gridView:(UzysGridView *)gridView didSelectCell:(UzysGridViewCell *)cell atIndex:(NSUInteger)index
{
    NSLog(@"Cell index %d",index);
}

**Comment by cloudjanak** [comment]
Thankx
